// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file gfs/v2/auth.proto (package gfs.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { User } from "./user_pb";
import { file_gfs_v2_user } from "./user_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gfs/v2/auth.proto.
 */
export const file_gfs_v2_auth: GenFile = /*@__PURE__*/
  fileDesc("ChFnZnMvdjIvYXV0aC5wcm90bxIGZ2ZzLnYyIi8KDExvZ2luUmVxdWVzdBINCgVlbWFpbBgBIAEoCRIQCghwYXNzd29yZBgCIAEoCSIeCg1Mb2dpblJlc3BvbnNlEg0KBXRva2VuGAEgASgJIkAKD1JlZ2lzdGVyUmVxdWVzdBIMCgRuYW1lGAEgASgJEg0KBWVtYWlsGAIgASgJEhAKCHBhc3N3b3JkGAMgASgJIj0KEFJlZ2lzdGVyUmVzcG9uc2USGgoEdXNlchgBIAEoCzIMLmdmcy52Mi5Vc2VyEg0KBXRva2VuGAIgASgJMoYBCgtBdXRoU2VydmljZRI2CgVMb2dpbhIULmdmcy52Mi5Mb2dpblJlcXVlc3QaFS5nZnMudjIuTG9naW5SZXNwb25zZSIAEj8KCFJlZ2lzdGVyEhcuZ2ZzLnYyLlJlZ2lzdGVyUmVxdWVzdBoYLmdmcy52Mi5SZWdpc3RlclJlc3BvbnNlIgBChwEKCmNvbS5nZnMudjJCCUF1dGhQcm90b1ABWjVnaXRodWIuY29tL2VyaGFoYWhhYS9nZnMtbXMvY29tbW9uL3Byb3RvL2dmcy92MjtnZnN2MqICA0dYWKoCBkdmcy5WMsoCBkdmc1xWMuICEkdmc1xWMlxHUEJNZXRhZGF0YeoCB0dmczo6VjJiBnByb3RvMw", [file_gfs_v2_user]);

/**
 * @generated from message gfs.v2.LoginRequest
 */
export type LoginRequest = Message<"gfs.v2.LoginRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message gfs.v2.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_gfs_v2_auth, 0);

/**
 * @generated from message gfs.v2.LoginResponse
 */
export type LoginResponse = Message<"gfs.v2.LoginResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message gfs.v2.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_gfs_v2_auth, 1);

/**
 * @generated from message gfs.v2.RegisterRequest
 */
export type RegisterRequest = Message<"gfs.v2.RegisterRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string password = 3;
   */
  password: string;
};

/**
 * Describes the message gfs.v2.RegisterRequest.
 * Use `create(RegisterRequestSchema)` to create a new message.
 */
export const RegisterRequestSchema: GenMessage<RegisterRequest> = /*@__PURE__*/
  messageDesc(file_gfs_v2_auth, 2);

/**
 * @generated from message gfs.v2.RegisterResponse
 */
export type RegisterResponse = Message<"gfs.v2.RegisterResponse"> & {
  /**
   * @generated from field: gfs.v2.User user = 1;
   */
  user?: User;

  /**
   * @generated from field: string token = 2;
   */
  token: string;
};

/**
 * Describes the message gfs.v2.RegisterResponse.
 * Use `create(RegisterResponseSchema)` to create a new message.
 */
export const RegisterResponseSchema: GenMessage<RegisterResponse> = /*@__PURE__*/
  messageDesc(file_gfs_v2_auth, 3);

/**
 * @generated from service gfs.v2.AuthService
 */
export const AuthService: GenService<{
  /**
   * @generated from rpc gfs.v2.AuthService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
  /**
   * @generated from rpc gfs.v2.AuthService.Register
   */
  register: {
    methodKind: "unary";
    input: typeof RegisterRequestSchema;
    output: typeof RegisterResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_gfs_v2_auth, 0);

