// @generated by protoc-gen-connect-es v1.5.0 with parameter "target=ts"
// @generated from file gfs/v2/auth.proto (package gfs.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { LoginRequest, LoginResponse, RegisterRequest, RegisterResponse } from "./auth_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service gfs.v2.AuthService
 */
export const AuthService = {
  typeName: "gfs.v2.AuthService",
  methods: {
    /**
     * @generated from rpc gfs.v2.AuthService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gfs.v2.AuthService.Register
     */
    register: {
      name: "Register",
      I: RegisterRequest,
      O: RegisterResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

