// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file gfs/v2/note.proto (package gfs.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import type { Empty, FieldMask } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty, file_google_protobuf_field_mask } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gfs/v2/note.proto.
 */
export const file_gfs_v2_note: GenFile = /*@__PURE__*/
  fileDesc("ChFnZnMvdjIvbm90ZS5wcm90bxIGZ2ZzLnYyIloKBE5vdGUSCgoCaWQYASABKAUSDQoFdGl0bGUYAiABKAkSDwoHY29udGVudBgDIAEoCRISCgpjcmVhdGVkX2F0GAQgASgJEhIKCnVwZGF0ZWRfYXQYBSABKAkiSQoQTGlzdE5vdGVzUmVxdWVzdBIOCgZwYXJlbnQYASABKAkSEQoJcGFnZV9zaXplGAIgASgFEhIKCnBhZ2VfdG9rZW4YAyABKAkiSQoRTGlzdE5vdGVzUmVzcG9uc2USGwoFbm90ZXMYASADKAsyDC5nZnMudjIuTm90ZRIXCg9uZXh0X3BhZ2VfdG9rZW4YAiABKAkiHgoOR2V0Tm90ZVJlcXVlc3QSDAoEbmFtZRgBIAEoCSItCg9HZXROb3RlUmVzcG9uc2USGgoEbm90ZRgBIAEoCzIMLmdmcy52Mi5Ob3RlIlAKEUNyZWF0ZU5vdGVSZXF1ZXN0Eg4KBnBhcmVudBgBIAEoCRIPCgdub3RlX2lkGAIgASgJEhoKBG5vdGUYAyABKAsyDC5nZnMudjIuTm90ZSIwChJDcmVhdGVOb3RlUmVzcG9uc2USGgoEbm90ZRgBIAEoCzIMLmdmcy52Mi5Ob3RlImAKEVVwZGF0ZU5vdGVSZXF1ZXN0EhoKBG5vdGUYASABKAsyDC5nZnMudjIuTm90ZRIvCgt1cGRhdGVfbWFzaxgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE1hc2siMAoSVXBkYXRlTm90ZVJlc3BvbnNlEhoKBG5vdGUYASABKAsyDC5nZnMudjIuTm90ZSIhChFEZWxldGVOb3RlUmVxdWVzdBIMCgRuYW1lGAEgASgJIjsKEkRlbGV0ZU5vdGVSZXNwb25zZRIlCgVlbXB0eRgBIAEoCzIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eTKBBAoLTm90ZVNlcnZpY2USWQoJTGlzdE5vdGVzEhguZ2ZzLnYyLkxpc3ROb3Rlc1JlcXVlc3QaGS5nZnMudjIuTGlzdE5vdGVzUmVzcG9uc2UiF4LT5JMCERIPL3YxYWxwaGExL25vdGVzElwKB0dldE5vdGUSFi5nZnMudjIuR2V0Tm90ZVJlcXVlc3QaFy5nZnMudjIuR2V0Tm90ZVJlc3BvbnNlIiCC0+STAhoSGC92MWFscGhhMS97bmFtZT1ub3Rlcy8qfRJiCgpDcmVhdGVOb3RlEhkuZ2ZzLnYyLkNyZWF0ZU5vdGVSZXF1ZXN0GhouZ2ZzLnYyLkNyZWF0ZU5vdGVSZXNwb25zZSIdgtPkkwIXOgRub3RlIg8vdjFhbHBoYTEvbm90ZXMSbgoKVXBkYXRlTm90ZRIZLmdmcy52Mi5VcGRhdGVOb3RlUmVxdWVzdBoaLmdmcy52Mi5VcGRhdGVOb3RlUmVzcG9uc2UiKYLT5JMCIzoEbm90ZTIbL3YxYWxwaGExL3tub3RlLmlkPW5vdGVzLyp9EmUKCkRlbGV0ZU5vdGUSGS5nZnMudjIuRGVsZXRlTm90ZVJlcXVlc3QaGi5nZnMudjIuRGVsZXRlTm90ZVJlc3BvbnNlIiCC0+STAhoqGC92MWFscGhhMS97bmFtZT1ub3Rlcy8qfUKHAQoKY29tLmdmcy52MkIJTm90ZVByb3RvUAFaNWdpdGh1Yi5jb20vZXJoYWhhaGFhL2dmcy1tcy9jb21tb24vcHJvdG8vZ2ZzL3YyO2dmc3YyogIDR1hYqgIGR2ZzLlYyygIGR2ZzXFYy4gISR2ZzXFYyXEdQQk1ldGFkYXRh6gIHR2ZzOjpWMmIGcHJvdG8z", [file_google_api_annotations, file_google_protobuf_empty, file_google_protobuf_field_mask]);

/**
 * @generated from message gfs.v2.Note
 */
export type Note = Message<"gfs.v2.Note"> & {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string content = 3;
   */
  content: string;

  /**
   * @generated from field: string created_at = 4;
   */
  createdAt: string;

  /**
   * @generated from field: string updated_at = 5;
   */
  updatedAt: string;
};

/**
 * Describes the message gfs.v2.Note.
 * Use `create(NoteSchema)` to create a new message.
 */
export const NoteSchema: GenMessage<Note> = /*@__PURE__*/
  messageDesc(file_gfs_v2_note, 0);

/**
 * @generated from message gfs.v2.ListNotesRequest
 */
export type ListNotesRequest = Message<"gfs.v2.ListNotesRequest"> & {
  /**
   * @generated from field: string parent = 1;
   */
  parent: string;

  /**
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 3;
   */
  pageToken: string;
};

/**
 * Describes the message gfs.v2.ListNotesRequest.
 * Use `create(ListNotesRequestSchema)` to create a new message.
 */
export const ListNotesRequestSchema: GenMessage<ListNotesRequest> = /*@__PURE__*/
  messageDesc(file_gfs_v2_note, 1);

/**
 * @generated from message gfs.v2.ListNotesResponse
 */
export type ListNotesResponse = Message<"gfs.v2.ListNotesResponse"> & {
  /**
   * @generated from field: repeated gfs.v2.Note notes = 1;
   */
  notes: Note[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message gfs.v2.ListNotesResponse.
 * Use `create(ListNotesResponseSchema)` to create a new message.
 */
export const ListNotesResponseSchema: GenMessage<ListNotesResponse> = /*@__PURE__*/
  messageDesc(file_gfs_v2_note, 2);

/**
 * @generated from message gfs.v2.GetNoteRequest
 */
export type GetNoteRequest = Message<"gfs.v2.GetNoteRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message gfs.v2.GetNoteRequest.
 * Use `create(GetNoteRequestSchema)` to create a new message.
 */
export const GetNoteRequestSchema: GenMessage<GetNoteRequest> = /*@__PURE__*/
  messageDesc(file_gfs_v2_note, 3);

/**
 * @generated from message gfs.v2.GetNoteResponse
 */
export type GetNoteResponse = Message<"gfs.v2.GetNoteResponse"> & {
  /**
   * @generated from field: gfs.v2.Note note = 1;
   */
  note?: Note;
};

/**
 * Describes the message gfs.v2.GetNoteResponse.
 * Use `create(GetNoteResponseSchema)` to create a new message.
 */
export const GetNoteResponseSchema: GenMessage<GetNoteResponse> = /*@__PURE__*/
  messageDesc(file_gfs_v2_note, 4);

/**
 * @generated from message gfs.v2.CreateNoteRequest
 */
export type CreateNoteRequest = Message<"gfs.v2.CreateNoteRequest"> & {
  /**
   * @generated from field: string parent = 1;
   */
  parent: string;

  /**
   * @generated from field: string note_id = 2;
   */
  noteId: string;

  /**
   * @generated from field: gfs.v2.Note note = 3;
   */
  note?: Note;
};

/**
 * Describes the message gfs.v2.CreateNoteRequest.
 * Use `create(CreateNoteRequestSchema)` to create a new message.
 */
export const CreateNoteRequestSchema: GenMessage<CreateNoteRequest> = /*@__PURE__*/
  messageDesc(file_gfs_v2_note, 5);

/**
 * @generated from message gfs.v2.CreateNoteResponse
 */
export type CreateNoteResponse = Message<"gfs.v2.CreateNoteResponse"> & {
  /**
   * @generated from field: gfs.v2.Note note = 1;
   */
  note?: Note;
};

/**
 * Describes the message gfs.v2.CreateNoteResponse.
 * Use `create(CreateNoteResponseSchema)` to create a new message.
 */
export const CreateNoteResponseSchema: GenMessage<CreateNoteResponse> = /*@__PURE__*/
  messageDesc(file_gfs_v2_note, 6);

/**
 * @generated from message gfs.v2.UpdateNoteRequest
 */
export type UpdateNoteRequest = Message<"gfs.v2.UpdateNoteRequest"> & {
  /**
   * @generated from field: gfs.v2.Note note = 1;
   */
  note?: Note;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask;
};

/**
 * Describes the message gfs.v2.UpdateNoteRequest.
 * Use `create(UpdateNoteRequestSchema)` to create a new message.
 */
export const UpdateNoteRequestSchema: GenMessage<UpdateNoteRequest> = /*@__PURE__*/
  messageDesc(file_gfs_v2_note, 7);

/**
 * @generated from message gfs.v2.UpdateNoteResponse
 */
export type UpdateNoteResponse = Message<"gfs.v2.UpdateNoteResponse"> & {
  /**
   * @generated from field: gfs.v2.Note note = 1;
   */
  note?: Note;
};

/**
 * Describes the message gfs.v2.UpdateNoteResponse.
 * Use `create(UpdateNoteResponseSchema)` to create a new message.
 */
export const UpdateNoteResponseSchema: GenMessage<UpdateNoteResponse> = /*@__PURE__*/
  messageDesc(file_gfs_v2_note, 8);

/**
 * @generated from message gfs.v2.DeleteNoteRequest
 */
export type DeleteNoteRequest = Message<"gfs.v2.DeleteNoteRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message gfs.v2.DeleteNoteRequest.
 * Use `create(DeleteNoteRequestSchema)` to create a new message.
 */
export const DeleteNoteRequestSchema: GenMessage<DeleteNoteRequest> = /*@__PURE__*/
  messageDesc(file_gfs_v2_note, 9);

/**
 * @generated from message gfs.v2.DeleteNoteResponse
 */
export type DeleteNoteResponse = Message<"gfs.v2.DeleteNoteResponse"> & {
  /**
   * @generated from field: google.protobuf.Empty empty = 1;
   */
  empty?: Empty;
};

/**
 * Describes the message gfs.v2.DeleteNoteResponse.
 * Use `create(DeleteNoteResponseSchema)` to create a new message.
 */
export const DeleteNoteResponseSchema: GenMessage<DeleteNoteResponse> = /*@__PURE__*/
  messageDesc(file_gfs_v2_note, 10);

/**
 * Generated according to https://cloud.google.com/apis/design/standard_methods
 *
 * @generated from service gfs.v2.NoteService
 */
export const NoteService: GenService<{
  /**
   * @generated from rpc gfs.v2.NoteService.ListNotes
   */
  listNotes: {
    methodKind: "unary";
    input: typeof ListNotesRequestSchema;
    output: typeof ListNotesResponseSchema;
  },
  /**
   * @generated from rpc gfs.v2.NoteService.GetNote
   */
  getNote: {
    methodKind: "unary";
    input: typeof GetNoteRequestSchema;
    output: typeof GetNoteResponseSchema;
  },
  /**
   * @generated from rpc gfs.v2.NoteService.CreateNote
   */
  createNote: {
    methodKind: "unary";
    input: typeof CreateNoteRequestSchema;
    output: typeof CreateNoteResponseSchema;
  },
  /**
   * @generated from rpc gfs.v2.NoteService.UpdateNote
   */
  updateNote: {
    methodKind: "unary";
    input: typeof UpdateNoteRequestSchema;
    output: typeof UpdateNoteResponseSchema;
  },
  /**
   * @generated from rpc gfs.v2.NoteService.DeleteNote
   */
  deleteNote: {
    methodKind: "unary";
    input: typeof DeleteNoteRequestSchema;
    output: typeof DeleteNoteResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_gfs_v2_note, 0);

