// @generated by protoc-gen-connect-es v1.5.0 with parameter "target=ts"
// @generated from file gfs/v2/note.proto (package gfs.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateNoteRequest, CreateNoteResponse, DeleteNoteRequest, DeleteNoteResponse, GetNoteRequest, GetNoteResponse, ListNotesRequest, ListNotesResponse, UpdateNoteRequest, UpdateNoteResponse } from "./note_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Generated according to https://cloud.google.com/apis/design/standard_methods
 *
 * @generated from service gfs.v2.NoteService
 */
export const NoteService = {
  typeName: "gfs.v2.NoteService",
  methods: {
    /**
     * @generated from rpc gfs.v2.NoteService.ListNotes
     */
    listNotes: {
      name: "ListNotes",
      I: ListNotesRequest,
      O: ListNotesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gfs.v2.NoteService.GetNote
     */
    getNote: {
      name: "GetNote",
      I: GetNoteRequest,
      O: GetNoteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gfs.v2.NoteService.CreateNote
     */
    createNote: {
      name: "CreateNote",
      I: CreateNoteRequest,
      O: CreateNoteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gfs.v2.NoteService.UpdateNote
     */
    updateNote: {
      name: "UpdateNote",
      I: UpdateNoteRequest,
      O: UpdateNoteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gfs.v2.NoteService.DeleteNote
     */
    deleteNote: {
      name: "DeleteNote",
      I: DeleteNoteRequest,
      O: DeleteNoteResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

