// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file gfs/v2/user.proto (package gfs.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gfs/v2/user.proto.
 */
export const file_gfs_v2_user: GenFile = /*@__PURE__*/
  fileDesc("ChFnZnMvdjIvdXNlci5wcm90bxIGZ2ZzLnYyIlUKBFVzZXISCgoCaWQYASABKAUSDAoEbmFtZRgCIAEoCRINCgVlbWFpbBgDIAEoCRIQCghwYXNzd29yZBgEIAEoCRISCgpjcmVhdGVkX2F0GAUgASgJQocBCgpjb20uZ2ZzLnYyQglVc2VyUHJvdG9QAVo1Z2l0aHViLmNvbS9lcmhhaGFoYWEvZ2ZzLW1zL2NvbW1vbi9wcm90by9nZnMvdjI7Z2ZzdjKiAgNHWFiqAgZHZnMuVjLKAgZHZnNcVjLiAhJHZnNcVjJcR1BCTWV0YWRhdGHqAgdHZnM6OlYyYgZwcm90bzM");

/**
 * @generated from message gfs.v2.User
 */
export type User = Message<"gfs.v2.User"> & {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: string password = 4;
   */
  password: string;

  /**
   * @generated from field: string created_at = 5;
   */
  createdAt: string;
};

/**
 * Describes the message gfs.v2.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_gfs_v2_user, 0);

